### ISSUE TITLE
Iuse, c # Encoding.ASCII.GetBytes (data) sent to nodejs tcp, which contains Chinese characters How do I transcoding

### ISSUE THREAD

**Issue by Messilimeng** [ashtuchkin/iconv-lite#100]

**Comment by ashtuchkin** [comment]
Sorry I don't understand. Could you elaborate?

**Comment by Messilimeng** [comment]
How do I decode chinese?

**Comment by ashtuchkin** [comment]
A sample is on the home page of this project (
https://github.com/ashtuchkin/iconv-lite). Basically you do `str =
iconv.decode(buf, '<encoding>');`, where `buf` is the raw data you read
from TCP socket (type Buffer). Most popular Chinese encoding is 'gbk', but
there could be some others as well, you'll need to check it.

--
Alexander Shtuchkin
