### ISSUE TITLE
Add CESU-8?

### ISSUE THREAD

**Issue by dougwilson** [ashtuchkin/iconv-lite#102]
Hi! So I really need to get CESU-8 implemented somewhere for use with old crap like various databases. Would you be willing to add CESU-8 support to this module :)?

**Comment by ashtuchkin** [comment]
The nodejs utf8 decoder should support it afaik. Could you try it?
Or do you need an encoder?

**Comment by dougwilson** [comment]
I need both an encoder and a decoder (because I need to write to the databases, not just read). The Node.js UTF-8 decoder does support CESU-8, yes. This is more about an encoder (though I believe Node.js utf8 only supports CESU-8 out of coincidence, rather than intention).

**Comment by ashtuchkin** [comment]
I think I saw references to CESU-8 in the Node code, so I tend to think it
was intentional.

About the encoder - if you need it quickly, you could use something like
this:
```
buf = Buffer.concat(str.split('').map(function(s) {return new Buffer(s);}));
```

Basically, CESU-8 is just a UTF-8 with UTF-16 surrogates encoded as a
separate chars.

I'll also add this to the encoding wish list and get to it when I have
time. Deal? :)

--
Alexander Shtuchkin

**Comment by dougwilson** [comment]
I tried that trick but it does not work. Node replaces all the surrogate pairs with the Unicode replacement character...

**Comment by ashtuchkin** [comment]
Works for me... Node v0.12.4
```
> str = "\uD801\uDC37"
'𐐷'
> buf = Buffer.concat(str.split('').map(function(s) {return new
Buffer(s);}));
<Buffer ef bf bd ef bf bd>
```

--
Alexander Shtuchkin

**Comment by ashtuchkin** [comment]
Ahh, yeah, that's the different character, sorry.

--
Alexander Shtuchkin

**Comment by dougwilson** [comment]
Right, yea, you can see it changed both surrogates to ef bf bd which is UTF-8 encoding of U+FFFD so decoding that just gives you two question marks instead of the original character, lol.

**Comment by ashtuchkin** [comment]
Fixed in e75dacaede131585e5e07268ae1467f40f02f990, published on npm as v0.4.11. Thanks for getting my attention to it!

**Comment by dougwilson** [comment]
```
$ node -pe 'require("iconv-lite").encode("yes \uD83D\uDC4D","cesu8")'
<Buffer 79 65 73 20 ed a0 bd ed b1 8d>
```

:joy:

**Comment by ashtuchkin** [comment]
Cool)
