### ISSUE TITLE
is it feasible to add an encoding extension in the run time?

### ISSUE THREAD

**Issue by kidwm** [ashtuchkin/iconv-lite#103]
I want to use big5-uao from https://moztw.org/docs/big5/table/uao250-b2u.txt

how to do this after `require('iconv-lite')`?

**Comment by ashtuchkin** [comment]
You could create an encoding definition JSON and add it to `iconv.encodings`, something like:
```javascript
iconv.encodings['big5uao'] = {
  type: '_dbcs',
  table: <your correspondence table>
}
```

Before matching encoding name, it's lowercased and stripped of all non-alphanum characters, so you should do that too when adding field to `iconv.encodings`.

Key points in code:
 * https://github.com/ashtuchkin/iconv-lite/blob/master/lib/index.js#L61
 * https://github.com/ashtuchkin/iconv-lite/blob/master/encodings/dbcs-data.js#L160
 * https://github.com/ashtuchkin/iconv-lite/tree/master/encodings/tables
 * https://github.com/ashtuchkin/iconv-lite/blob/master/generation/utils.js#L59  (table format)

**Comment by kidwm** [comment]
Thanks, I'll try to make it out.
