### ISSUE TITLE
CESU-8 decoding does not work in Node.js 4

### ISSUE THREAD

**Issue by dougwilson** [ashtuchkin/iconv-lite#106]
It looks like since this module was just using Node.js's "utf-8" encoding to do CESU-8, when they removed this from Node.js 4, it means that this module can no longer decode CESU-8.

From @bnoordhuis :

> Yes, that was removed in https://github.com/nodejs/node/commit/70d1f32 ("deps: update v8 to 4.4.63.9"):
>
> > Notable backwards incompatible changes are the removal of the smalloc module and dropped support for CESU-8 decoding. CESU-8 support can be brought back if necessary by doing UTF-8 decoding ourselves.
>
> Long story short: V8 string functions no longer accept CESU-8 as input. Node would have to implement its own UTF-8-to-UTF-16 encoder.

**Comment by ashtuchkin** [comment]
Thanks for reporting it! Fixed in 15f2554c97c79f259ccbdc95a19209f25d13f217, will soon push to npm.

**Comment by dougwilson** [comment]
Awesome, thank you, @ashtuchkin !

P.S. whatever happens in #107, please do not even think about unpublishing 0.4.12 from npm, pretty please, as I am publishing a module that depends on 0.4.12 :)

**Comment by ashtuchkin** [comment]
I guarantee :)

--
Alexander Shtuchkin
