### ISSUE TITLE
iconv.decodeStream() ignores encoding option

### ISSUE THREAD

**Issue by dominiklessel** [ashtuchkin/iconv-lite#110]
I'm wondering why the encoding option is overwritten with `utf8` and completely ignored:

See [streams.js#L79](https://github.com/ashtuchkin/iconv-lite/blob/master/lib/streams.js#L79)

**Comment by ashtuchkin** [comment]
This is by design. We must set this to utf8 to avoid Node interfering with decoding process. Actual encoding is set inside the converter (`conv` parameter) in [line 15](https://github.com/ashtuchkin/iconv-lite/blob/master/lib/streams.js#L15)

**Comment by dominiklessel** [comment]
Ah okay.

I tried a streaming conversion of S3 objects (CSV files) and the AWS.S3.upload() method, which accepts a stream object, is blowing up, when used with iconv-lite. After forking and editing streams.js#L79 to accept `encoding: null` it worked as expected.

```
TypeError: Object foo|bar|baz has no method 'copy'
at Function.Buffer.concat (buffer.js:499:9)
at ManagedUpload.fillStream (/var/task/node_modules/aws-sdk/lib/s3/managed_upload.js:386:21)
at IconvLiteDecoderStream.<anonymous> (/var/task/node_modules/aws-sdk/lib/s3/managed_upload.js:169:28)
at IconvLiteDecoderStream.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickDomainCallback (node.js:486:13)
```

**Comment by ashtuchkin** [comment]
​If the stream you're piping to ​only supports buffers (encoding=null),
then I'd suggest the following:

```
source.pipe(iconv.decodeStream(encoding)).pipe(iconv.encodeStream('utf8')).pipe(aws_upload_whatever)

```

The rule of thumb here is the following - decode converts encoded binary to
js string; encode converts js string to encoded binary. To convert binary
-> binary, you need to decode, then encode.


--
Alexander Shtuchkin

**Comment by dominiklessel** [comment]
Thank you for your clarification! Maybe this should be added to the readme :+1:

**Comment by ashtuchkin** [comment]
I kinda tried to cover that in [wiki](https://github.com/ashtuchkin/iconv-lite/wiki), but any suggestions welcome!
