### ISSUE TITLE
Auto-detect utf8

### ISSUE THREAD

**Issue by danielgindi** [ashtuchkin/iconv-lite#113]
Hello!

Is there a way to auto-detect utf8?

Consider a case like this:
1. You want to support ANSI encodings, like windows' default ANSI->Unicode mapping.
2. You pass "1255" to `iconv.decodeStream`
3. You expect it to convert using 1255, *unless* it found a UTF8 BOM or UTF8 codepoints along the way.

So basically what I'm trying to find out is how to do UTF8 detection like most programs do today - and falling back to an ANSI encoding.

Is that doable in iconv-lite?

**Comment by ashtuchkin** [comment]
If your case is not very performance-sensitive and not streaming, you can do something like this:
```
var bomUsed = false;
var res = iconv.decode(buf, "utf8", {stripBOM: function() { bomUsed = true });
if (!bomUsed)
  res = iconv.decode(buf, "1255");
```

stripBOM parameter acts both as flag and as a callback that is called when BOM exists.

If streaming is required, then you can write small wrapper that would do the detection, similar to [StripBOMWrapper](https://github.com/ashtuchkin/iconv-lite/blob/master/lib/bom-handling.js#L28).

**Comment by danielgindi** [comment]
Thanks for your quick reply!

I have already created a module that wraps iconv-lite and jschardet with a stream that autodetects and falls back.

https://github.com/danielgindi/node-autodetect-decoder-stream

**Comment by ashtuchkin** [comment]
Thanks Daniel! Added the your module to BOM handling section of readme.

**Comment by danielgindi** [comment]
That's nice :)
It actually tries to detect any encoding using `jschardet` so BOM is the least of it
