### ISSUE TITLE
How can I use iconv-lite with superAgent?

### ISSUE THREAD

**Issue by hanzichi** [ashtuchkin/iconv-lite#116]
It works quite well when using `http.get(..., ...)`, but I wonder that how I can use iconv-lite with [superAgent](http://visionmedia.github.io/superagent/) or request module? I'd prefer **superAgent** when setting http request. Thanks in advance!

**Comment by ashtuchkin** [comment]
There seems to be a module for it: https://www.npmjs.com/package/superagent-charset

**Comment by hanzichi** [comment]
thanks, it really works well ! Thanks again !

**Comment by ashtuchkin** [comment]
You're welcome :)
