### ISSUE TITLE
builder error after switched the node version from v5.9.0 to v6.0.0

### ISSUE THREAD

**Issue by hujb2000** [ashtuchkin/iconv-lite#119]
Before the node v6.0.0, the repository https://github.com/hujb2000/easynode-ipc.git , Do npm  install is always ok , but when I upgrade node to the last version v6.0.0,  when npm install it console such logs,
Can you help me ?

 
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/hujiabao/.nvm/versions/node/v6.0.0/bin/node" "/Users/hujiabao/.nvm/versions/node/v6.0.0/bin/npm" "update"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.1.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hujiabao/workspace_docker/icp/easynode-ipc/npm-debug.log

**Comment by ashtuchkin** [comment]
Hello Allen! Please refer to "iconv" package maintainer. This is a
different package named "iconv-lite".

Alex

**Comment by hujb2000** [comment]
I see , Thanks
