### ISSUE TITLE
utf8mb4 support?

### ISSUE THREAD

**Issue by sidorares** [ashtuchkin/iconv-lite#120]
Is [mysql utf8mb4](https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html)  supported? If not, would it be easy / possible to add support? Or maybe someone knows a simpler way to do utf8mb4->utf8 conversion efficiently in node?

**Comment by sidorares** [comment]
never mind, that was mysql issue ( 4-byte chars used in field name and mysql returned '3f203f203f203f203f203f203f203f203f203f203f203f203f203f203f20' and I thought results of `toString('utf8')` are incorrect but in fact it was actually '? ? ? ? ? ? ? ? ? ? ? ? ? ? ?' in that string )

**Comment by ashtuchkin** [comment]
Glad you solved it :)

--
Alexander Shtuchkin

**Comment by sidorares** [comment]
my main issue is not solved, but at least I know now that I don't need iconv to convert from utf8mb4, it's just utf8 - so nothing to do with iconv-lite :)

**Comment by ashtuchkin** [comment]
Yep ok, good luck :)

--
Alexander Shtuchkin
