### ISSUE TITLE
Subscript operator does not work in newer versions of Node.js

### ISSUE THREAD

**Issue by pluma** [ashtuchkin/iconv-lite#123]
The code heavily relies on the subscript operator (i.e. accessing byte offsets as properties directly) which doesn't seem to be supported in Node.js 6 and probably even earlier than that.

As far as I can tell all subscript operations need to be replaced with `readUInt8` and `writeUInt8` as appropriate.

I'm not sure when I will have the time but I may end up writing a PR to fix this myself if there are no other takers/objections.

**Comment by ashtuchkin** [comment]
hmm.. just installed node v6.3 and run `npm test` and it looks fine.. (needed to update iconv to latest version) Are you having any problems with it?

**Comment by ashtuchkin** [comment]
Also see https://nodejs.org/api/buffer.html#buffer_buf_index

**Comment by pluma** [comment]
Okay, strange. I was just able to verify that this actually works in Node.js 6 just fine. I was debugging buffer issues yesterday and was unable to write to buffers using the subscript operator but it must have been caused by something else. Sorry for the noise.

**Comment by ashtuchkin** [comment]
No problem :)

--
Alexander Shtuchkin
