### ISSUE TITLE
missing encoding from mysql encodings list

### ISSUE THREAD

**Issue by sidorares** [ashtuchkin/iconv-lite#125]
hi, 
I'm adding support for non-utf encorings to mysql2 ( https://github.com/sidorares/node-mysql2/pull/374 ) and currently trying to map between mysql charsets and iconv encoding names. Some encodings seem to be missing ( macroman, keybcs2 ) for example.

It seems that all of them are described here - https://github.com/twitter/mysql/tree/master/sql/share/charsets

Would you be interested in adding them? Perhaps script to import this data automatically? Is there a documentation on how to add new encoding table to iconv-lite?

**Comment by ashtuchkin** [comment]
Hey! Are these completely new encodings or just aliases to existing ones?
Btw, iconv-lite supports macroman directly.

--
Alexander Shtuchkin

**Comment by sidorares** [comment]
missed `macroman`, it's supported indeed. How about `keybcs2` ?
They all must be old encodings but I'm not sure is the names are canonical and you might have them under different name

**Comment by ashtuchkin** [comment]
That's an obscure encoding :) https://en.wikipedia.org/wiki/Kamenick%C3%BD_encoding
Googling it shows mysql codebase and ~7000 old pages, which is pretty small, so I'm not sure it makes sense to add it to iconv-lite directly. 

Have no fear though! You can append encoding from outside of iconv-lite, in your own code, like this:
```js
var iconv = require('iconv-lite');
iconv.getCodec('ascii'); // Lazy-load existing encodings to fill out iconv.encodings dict.

// Now add new encodings
// key in this dictionary is lowercase name of encoding with all non-alphanumeric symbols stripped
// (i.e. name might be "abc-XYZ", then the key is "abcxyz", see more examples in /encodings directory)
iconv.encodings["myencoding"] = {
        "type": "_sbcs",  // Single-byte encoding.
        // "chars" is either 256 characters of encoding, or just top 128, if lower 128 is same as ascii.
        "chars": "ÄĀāÉĄÖÜáąČäčĆćéŹźĎíďĒēĖóėôöõúĚěü†°Ę£§•¶ß®©™ę¨≠ģĮįĪ≤≥īĶ∂∑łĻļĽľĹĺŅņŃ¬√ńŇ∆«»… ňŐÕőŌ–—“”‘’÷◊ōŔŕŘ‹›řŖŗŠ‚„šŚśÁŤťÍŽžŪÓÔūŮÚůŰűŲųÝýķŻŁżĢˇ"
};

// Also you can add encoding aliases
iconv.encodings["myawesomeencoding"] = "myencoding";

// Now you can use the new encodings to actually encode/decode stuff.
buf = iconv.encode("myencoding", "input string");
```

(Alternatively, you can say that you don't support it as it's very obscure :) )

**Comment by sidorares** [comment]
yes, it's probably too mysql specific to be part of iconv-lite.
I think I'll convert xml to iconv encodings and distribute them with mysql2 package and lazy load when requested

Thanks for example!
