### ISSUE TITLE
Syntax Error in gb18030-ranges.json  : Unexpected Token

### ISSUE THREAD

**Issue by GeekAb** [ashtuchkin/iconv-lite#128]
I am getting following error in gb18030-ranges.json :

Error transforming picker.js/node_modules/iconv-lite/encodings/tables/gb18030-ranges.json with 'babel' plugin.

SyntaxError: picker.js/node_modules/iconv-lite/encodings/tables/gb18030-ranges.json: Unexpected token (1:9)

Versions :
iconv-lite@0.4.13 
node@6.6.0

I tried removing content of same file and error goes and iconv-lite is included as dependency of another module I am using "gulp-pipeline".

Any possible fix for this?

**Comment by ashtuchkin** [comment]
Hmm, I checked it and it looks like `gb18030-ranges.json` is a perfectly valid json file. I think it's either a file corruption on your drive, or a bug in babel plugin. Never seen this error before. Let me know if you need more help.
