### ISSUE TITLE
iconv-lite@0.4.14 breaks build ⚠️ 

### ISSUE THREAD

**Issue by felixfbecker** [ashtuchkin/iconv-lite#137]
0.4.14 includes TypeScript definition files that have a triple-slash reference to the "node" typings. Triple slash references are a thing of the past, they are only used inside DT to declare dependencies. It doesn't work with included definition files:

https://travis-ci.org/felixfbecker/vscode-php-debug/jobs/177567952#L877

This line needs to be removed:
https://github.com/ashtuchkin/iconv-lite/blob/master/lib/index.d.ts#L6

**Comment by ashtuchkin** [comment]
Thanks for the report, will look into it asap. Meanwhile, can you check
that removing that line actually fixes the build?

cc @larssn

**Comment by ashtuchkin** [comment]
I.e. is everything else working?

**Comment by felixfbecker** [comment]
Yes, they are correct otherwise. Removing the line fixes everything.

(Sidenote: Please do not make the mistake of adding `@types/node` as a dependency - this mistake has been done a lot of times already and broke a lot of builds too. It's not the right solution)

**Comment by ashtuchkin** [comment]
I published v0.4.15 with this fix. Could you check it? 

Thanks again for quick response!

**Comment by felixfbecker** [comment]
Fixed https://travis-ci.org/felixfbecker/vscode-php-debug/builds/177751114

**Comment by larssn** [comment]
@ashtuchkin @felixfbecker 
This change has broken my Angular 2 app.

Reading up on whether triple slashes are deprecated didn't reveal anything:
https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

> The /// <reference path="..." /> directive is the most common of this group. It serves as a declaration of dependency between files.

I know we've switched to the @types/module format in package.conf, but this is different.

The typescript compiler (v2.0.10) no longer knows about the node built-ins, like Buffer, stream etc, and thus refuses to transpile, in my case.

```
/node_modules/iconv-lite/lib/index.d.ts, line: 6
           Cannot find module 'stream'.
```

**Comment by felixfbecker** [comment]
@larssn I did not say it is deprecated, but legacy, because it is not needed anymore. TS picks up files automatically. Node is a global definition, it cannot get added to dependencies. You need to install it in your project manually, through whatever mechanism (like `typings` or `npm`) and ensure it is included in your project by tsconfig.json settings. Adding a triple slash reference is assuming a location for the node typings, which is wrong.

**Comment by larssn** [comment]
But this gist of this change boils down to me having to add a bunch of extra definitions manually then. Can't see how that is supposed to be an improvement, legacy or not.

**Comment by felixfbecker** [comment]
No, you had to remove the definitions before too. Just because there is a /// reference doesn't make the node typings magically install themselves. You still need to install them.

**Comment by larssn** [comment]
You sure thats also true for node internals? I didn't install the .d.ts files for those before.

**Comment by felixfbecker** [comment]
Then you were probably lucky that some other module added them as a dependency (even though it shouldn't)

**Comment by larssn** [comment]
No, the definitions weren't there before, I checked.

Look, seeing as typescript runs in a node environment, it makes sense that it would know about the built-in node modules, IF told to look for them. I'm no expert on the latest changes in typescript and how definitions should and shouldn't look, because the docs are in constant flux; all I do know is this change broke our build, and its the only change to it.

I'll fork this, and go back to using triple-slashes until its 100% clear what the correct approach is, going forward.

Adding that single line fixes my problems, I've just tested it.
I'm sorry it caused problems for you.

**Comment by felixfbecker** [comment]
Definitions need to be installed. _There are no declarations bundled with TypeScript_.

**Comment by larssn** [comment]
Well then, I can't explain why the triple-slash fixes my problem then.

**Comment by ashtuchkin** [comment]
Just checked it myself on a small sample project and it did compile successfully after installation of "@types/node" to parent project. Typescript 2.1, Node 6.5.
