### ISSUE TITLE
Not doing the conversion

### ISSUE THREAD

**Issue by helloncanella** [ashtuchkin/iconv-lite#139]
I'm fetching a xml encoded in ISO-8859-1.

As long as the fetching is completed I'm trying to convert it to UTF-8.

```javascript
const iconv = require('iconv-lite');

fetch('http://www.band.uol.com.br/rss/colunista_64.xml')
  .then(res => res.text())
  .then(text => {
     const decodedText = iconv.decode(new Buffer(text), 'latin1')
             , output = iconv.encode(decodedText, 'utf8')
      console.log(output.toString())
})
```

The problem is: all especial characters of the body is being replaced by "¿½"

**Comment by ashtuchkin** [comment]
Hey, it looks like res.text() is already decoding the request body with
either UTF8 or encoding provided in headers.

To fix it, you might want to use res.arrayBuffer() (
https://developer.mozilla.org/en-US/docs/Web/API/Body/arrayBuffer), then
convert it to Buffer and provide to decode().

Let me know if it works.

**Comment by helloncanella** [comment]
Thank you. That approach works.
