### ISSUE TITLE
GB2312 to UTF-8 from node c++ addon (sent as JSON)

### ISSUE THREAD

**Issue by sulliwane** [ashtuchkin/iconv-lite#140]
I have a node.js c++ addon that has a callback where it receives a **GB2312 encoded char array** called **ErrorMsg**, here is the type definition:
```cpp
typedef char ErrorMsg[81]; // this is GB2312 inside!!
```
And here is the definition of the callback (I'm putting the ErrorMsg char array into a JSON string):
```cpp
void Spi::OnCallback(ErrorMsg *errorMsg) {
    json data = json({}); // prepare the JSON obj
    data["errorMsg"] = std::string(errorMsg); // NOT GOOD: convert char arr to str, and store in JSON
    writeToNode(data.dump()); // here I'm sending the JSON to JavaScript space
}
```
## Requirements
1. I want to convert GB2312 to UTF-8 in the JavaScript space. I don't want to use libiconv in c++. 
2. I have to use JSON to communicate between c++ space and JS space.

I plan to use iconv-lite to do the conversion (because it's lite, it's pure JS, and it's awsome ;) but I'm not sure how I should send the data from c++ to JS space, and that will support the JSON serializing/deserialize.....as a base64 string?

My guess is that I need to do:
1. encode the GB2312 char arr [to base64 in c++](http://stackoverflow.com/questions/342409/how-do-i-base64-encode-decode-in-c), 
2. then serialize to JSON in c++: ```data.dump()```.
3. deserialize to JS Object: ```const myObj = JSON.parse(json);```.
4. create a node buffer: ```const buff = Buffer.from(myObj.errMsg, 'base64');```.
5. decode to utf8: ```const utf8String = iconv.decode(buff, 'GB2312');```

Do you think this will work?

Many thanks for your help!

note: I use [this c++ json lib](https://github.com/nlohmann/json).

**Comment by ashtuchkin** [comment]
Not really proficient in C++ node coding, but can't you create a `Buffer` in C++ land? or `Uint8Array`? That would be the most efficient. 

If it's not possible or you really need to use json (and not just JS object), then your method should definitely work.

Tip: the `utf8String` you mention in step 5 is actually a regular JS String. It usually doesn't matter which encoding is used internally (utf16), so it's better to name it just `errorString`.

**Comment by sulliwane** [comment]
Ok, so I just tried and using base64 works fine ! Yay

My js string has a of null charachter at the end (\u000) like 20. These are present in the base64 string as well (AAAAAAAA....) so I guess my c++ base64 conversion function needs some reworking, until then I just remove them in JS space with ```string.replace(/\0/g, '')```.

Many thanks! iconv-lite is really great...

**Comment by ashtuchkin** [comment]
Great to hear it works!
