### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by jnfsmile** [ashtuchkin/iconv-lite#141]
When running a few grunt commands the following outputs (and operation fails):

```
<--- Last few GCs --->

   26221 ms: Mark-sweep 1380.5 (1435.1) -> 1378.6 (1434.3) MB, 239.0 / 0.0 ms [allocation failure] [GC in old space requested].
   26417 ms: Mark-sweep 1378.6 (1434.3) -> 1378.6 (1403.3) MB, 184.7 / 0.0 ms [last resort gc].
   26620 ms: Mark-sweep 1378.6 (1403.3) -> 1378.6 (1403.3) MB, 202.8 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000203718CFB61 <JS Object>
    1: slowToString [buffer.js:459] [pc=0000001E7D229615] (this=000001CF62344329 <an Uint8Array with map 00000253B5406569>,encoding=00000203718DBC89 <String[4]: utf8>,start=0,end=974314)
    2: arguments adaptor frame: 1->3
    3: fromEncoding(aka fromInternalEncoding) [PROJECT\node_modules\grunt\node_modules\iconv-lite\index.js:~123...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

Any way around it?

We are not using iconv-lite explicitly, it's a dependency somewhere.

**Comment by ashtuchkin** [comment]
The library itself has pretty reasonable memory footprint (several megabytes at most), so I assume that grunt is trying to process too large file. 

There are several solutions I see:
 1. Make sure all files in your project is utf8, so that grunt doesn't need to convert anything.
 2. Change grunt or your Gruntfile to use streaming iconv-lite API.

**Comment by jnfsmile** [comment]
Can you explain how to configure that in Gruntfile? Couldn't find a reference to that.

**Comment by ashtuchkin** [comment]
I mean, if you use iconv directly in Gruntfile, then you can change it to use streaming api. Otherwise, if it's some internal-to-grunt operation, then the only way is to change grunt itself.
