### ISSUE TITLE
ISO-8859-1 encoding/decoding in browser is incorrect 

### ISSUE THREAD

**Issue by DanielHuisman** [ashtuchkin/iconv-lite#142]
I discovered whilst attempting to decode a ISO-8859-1 string that it produces incorrect results. Down below is an example that illustrates the problem and shows the encoding is incorrect as well. (Running `iconv-lite@0.14.5`)

**Example:**
```js
const enc = iconv.encode(Buffer.from('test'), 'ISO-8859-1');
console.log(Buffer.from('test'), enc, iconv.decode(enc, 'ISO-8859-1'));
```

**Output:**
```
[116, 101, 115, 116]
[63, 63, 63, 63]
"ŸŸŸŸ"
```

**Comment by ashtuchkin** [comment]
Thanks for the detailed report Daniel!

I just checked on my machine and it seem to work fine (iconv-lite@0.4.15, node@v7.4.0):
```
> const enc = iconv.encode(Buffer.from('test'), 'ISO-8859-1');
undefined
> console.log(Buffer.from('test'), enc, iconv.decode(enc, 'ISO-8859-1'));
<Buffer 74 65 73 74> <Buffer 74 65 73 74> 'test'
undefined
```

The library is fully covered with tests for all encodings, plus ISO-8859-1 is a popular one and haven't changed for years, so I presume something might be wrong with your environment.

Specifically, I'm wondering why the buffers are printed like arrays, not the regular `<Buffer ...>`. Could it be that some other library is monkey-patching Buffer? Which version of node are you using? Could you try to reinstall the library (I've seen a partial/screwed installs before)?

**Comment by DanielHuisman** [comment]
I'm running this in the browser using Browserify (and Babelify for ES6 support). 
Apparently `Buffer.from('test')` returns a `Uint8Array`, found using `console.log(Buffer.from('test')[Symbol.toStringTag])`.

I also looked at the code generated by Browserify and found it uses the [buffer module](https://github.com/feross/buffer), which according to their "how it works" section returns `Uint8Array` instances with a modified prototype to support all Buffer functions. So I guess this is the expected behaviour and also the reason the browser prints them as plain arrays.

**Comment by ashtuchkin** [comment]
Ok, makes sense. I'll try to reproduce it in a browser.

Meanwhile, could you try again with a first argument to `encode` being a string, not buffer? When you encode something, you convert from string to buffer; when decoding - buffer to string.

**Comment by DanielHuisman** [comment]
Same result when using a string (`test`), it's encoded as `[63, 63, 63, 63]`

**Comment by ashtuchkin** [comment]
yep, thanks. 63 is ascii for "?"

**Comment by ashtuchkin** [comment]
I managed to reproduce it. Turns out, when Chrome loads javascript files, it defaults to latin1 encoding, but iconv-lite source files require utf-8. 

To fix it, one of the following needs to be done:
 * add `<meta charset="utf-8">` to the html file. 
 * use `<script src="your-file.js" charset="utf-8"></script>` to load the script.
 * add `Content-type: application/javascript; charset=utf-8` header to the http request of js file.

Let me know if it helped.

**Comment by DanielHuisman** [comment]
Thanks, adding `<meta charset="utf-8">` fixed it. Weird that UTF-8 still isn't the default encoding. Might be useful to include this somewhere in the documentation for browser support.

**Comment by ashtuchkin** [comment]
Yep I will add a note in readme and a runtime warning. Thanks!

**Comment by ashtuchkin** [comment]
Note: added a warning when this situation arises, with a link to relevant [wiki page](https://github.com/ashtuchkin/iconv-lite/wiki/Javascript-source-file-encodings)

**Comment by Bigquin21** [comment]
> I discovered whilst attempting to decode a ISO-8859-1 string that it produces incorrect results. Down below is an example that illustrates the problem and shows the encoding is incorrect as well. (Running `iconv-lite@0.14.5`)
> 
> **Example:**
> 
> ```js
> const enc = iconv.encode(Buffer.from('test'), 'ISO-8859-1');
> console.log(Buffer.from('test'), enc, iconv.decode(enc, 'ISO-8859-1'));
> ```
> 
> **Output:**
> 
> ```
> [116, 101, 115, 116]
> [63, 63, 63, 63]
> "ŸŸŸŸ"
> ```
