### ISSUE TITLE
Crashes IntelliJ

### ISSUE THREAD

**Issue by PaulBGD** [ashtuchkin/iconv-lite#143]
This is less of an issue and more of a congratulations. You just managed to break one of the biggest IDEs!

cp950.json seems to do the trick.

**Comment by ashtuchkin** [comment]
Hehe I like your way of thinking :)

Should it be a filed to IntelliJ then? AFAIK cp950 is a valid utf-8 json file.

**Comment by PaulBGD** [comment]
Yep, there's an issue for it already: https://youtrack.jetbrains.com/issue/IDEA-152656

**Comment by ashtuchkin** [comment]
Cool cool :)
