### ISSUE TITLE
Help please with encoding in a Node js https Post response.

### ISSUE THREAD

**Issue by louise-r-blue** [ashtuchkin/iconv-lite#144]
Hi & hope you can help:/

I have been having a hard time trying to work through some encoding issues.

I am using Electron with Node.js https. The app Posts a request to a Soap webservice.

I receive a status 200, correct Headers and response. However the response is a garbled twisted string of weird characters as in my screenshot.
![screenshot_characters](https://cloud.githubusercontent.com/assets/15900463/22050542/a48dc25e-dda0-11e6-9409-ddc5e391cfe3.png)

. 

Am trying iconv-lite but with no success. I am using Node v6.9.2, linux and npm 3.10.9.

Really appreciate any help

**Comment by ashtuchkin** [comment]
Hey, this doesn't look like text encoding. Could it be gzipped? Could you
post the whole response with headers?

--
Alexander Shtuchkin

**Comment by louise-r-blue** [comment]
Here is the post request code that I forgot to include earlier. I also realise iconv-lite may not work with my Node version (so I may upgrade) but any help would do.
![post_req](https://cloud.githubusercontent.com/assets/15900463/22055338/92923cbe-ddbf-11e6-9418-d2088dbc419d.png)

**Comment by ashtuchkin** [comment]
Thanks! Can you try to remove line with "Accept-Encoding" from your request
headers and try again? I think server returns gzipped data now.

--
Alexander Shtuchkin

**Comment by louise-r-blue** [comment]
Oh gosh that is it! Thank you ashtuchkin  :)
