### ISSUE TITLE
Support React Native

### ISSUE THREAD

**Issue by williams-voon** [ashtuchkin/iconv-lite#150]
Hi,

In this file 'Buffer' is not defined.
/iconv-lite/encodings/dbcs-codec.js

I think the line should be added at head of the file.
const { Buffer } = require('buffer') 

or ES6: import { Buffer }  from 'buffer'

Regards,
Williams

**Comment by ashtuchkin** [comment]
Thanks for the report, Williams!

Usually in Node environment Buffer is defined globally.. what environment
are you using?

Alex

On Apr 16, 2017 5:30 AM, "williams-voon" <notifications@github.com> wrote:

Hi,

In this file 'Buffer' is not defined.
/iconv-lite/encodings/dbcs-codec.js

I think the line should be added at head of the file.
const { Buffer } = require('buffer')

or ES6: import { Buffer } from 'buffer'

Regards,
Williams

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ashtuchkin/iconv-lite/issues/150>, or mute the thread

**Comment by williams-voon** [comment]
Hi Alex,

I am using React Native.

Regards,
Williams Voon

**Comment by larssn** [comment]
Yeah `Buffer` is a node built-in, no need to import.

Doesn't seem like you are using typescript, and I have no experience with react, otherwise I'd recommend doing:

`npm install @types/node`

**Comment by ashtuchkin** [comment]
@williams-voon I added explicit require()-s of buffer module, should now work, could you please check it?

To check, please install two new modules: `buffer` and `stream`, then install `iconv-lite` from master - use something like this in your `package.json`:
```
{
  "dependencies": {
    .. your deps ..
    "iconv-lite": "ashtuchkin/iconv-lite#master",
  }
}
```

**Comment by williams-voon** [comment]
@ashtuchkin 

I tried following steps.

1. Update package.json, and content is listed below:

```son
"dependencies": {
    "buffer": "^5.0.6",
    "iconv-lite": "ashtuchkin/iconv-lite#master",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "stream": "0.0.2"
  },
```

2. Remove the folder: node_modules
```
rm -fr node_modules
```
3. Install again
```
npm install
```

4. And then run my JS code in React Native project. The code listed below:
```javascript
    let buf =  iconv.encode('安安要乖乖\n', 'GBK' );
    let str=iconv.decode(buf,'GBK');
    console.log(str);
```

The code works as expected, and no error found.

So I think the problem has been solved. Thank you very much!

**Comment by ashtuchkin** [comment]
Released iconv-lite v0.4.16 with the fix. Thanks!

**Comment by flyher** [comment]
@ashtuchkin 
In react-native , when i use axios(arraybuffer) to get html (gb2312) source, the iconv-lite helped me.
Thank you for your good job.

share my code , maybe it can help more people:
```html
import axios from 'axios';
import iconv from 'iconv-lite';
import { Buffer } from 'buffer';

fetchHtml(){
    return axios({
      method: 'get',
      url: baseurl,
      responseType: 'arraybuffer'
    })
      .then((response) => {
        let html_ = iconv.decode(new Buffer(response.data), 'gbk');

        this.setState({
          html_: html_,
        });
      })
      .catch((error) => {
        console.error(error);
      });
}

```

**Comment by ashtuchkin** [comment]
Thanks @flyher!

**Comment by ililysong** [comment]
How can I import iconv-lite?
