### ISSUE TITLE
How to use it in the browser?

### ISSUE THREAD

**Issue by imsheng** [ashtuchkin/iconv-lite#151]
can be more specific? How to use the browserify

**Comment by ashtuchkin** [comment]
You can use any guide to browserify on the internets, like the following:
https://medium.com/@christopherphillips_88739/a-beginners-guide-to-browserify-1170a724ceb2
https://writingjavascript.org/posts/introduction-to-browserify
https://github.com/substack/browserify-handbook

And then just require this library and use it.
