### ISSUE TITLE
Something strange in detecting utf8 webpage

### ISSUE THREAD

**Issue by showwell0120** [ashtuchkin/iconv-lite#152]
When I test this page:
https://www.wired.com/2017/04/just-pair-11-radio-gadgets-can-steal-car/

and my code is as below:
<pre>
request({url: result.url, encoding: null}, (error, response, html)=>{
    var enc = charset(res.headers, html)
    enc = enc || jschardet.detect(html).encoding
    console.log("encoding: " + enc)
})
</pre>

It always return "null". But when I use `document.charset` in chrme dev tool, it return `UTF-8`
Can somebody fix it?

**Comment by ashtuchkin** [comment]
Not sure how iconv-lite is involved here.. :)
