### ISSUE TITLE
regression in node 8

### ISSUE THREAD

**Issue by sidorares** [ashtuchkin/iconv-lite#154]
added node 8 to node-mysql2 build and one of cesu8 tests fails now. Simple example to reproduce:

node 0.10.48 ( any pre 8.x )
```
> var iconv = require('iconv-lite')
> iconv.decode(Buffer('eda0bdedb2a9', 'hex'), 'cesu8')
'💩'
> Buffer(iconv.decode(Buffer('eda0bdedb2a9', 'hex'), 'cesu8'))
<Buffer f0 9f 92 a9>
```

node 8.1.0:
```
> var iconv = require('iconv-lite')
undefined
> iconv.decode(Buffer('eda0bdedb2a9', 'hex'), 'cesu8')
'��'
> Buffer.from(iconv.decode(Buffer.from('eda0bdedb2a9', 'hex'), 'cesu8'))
<Buffer ef bf bd ef bf bd>
```

**Comment by ashtuchkin** [comment]
Thanks for the report! I reproduced it and will fix soon.

I'll need to replace the check here: https://github.com/ashtuchkin/iconv-lite/blob/master/encodings/internal.js#L38  to something like `new Buffer('eda0bdedb2a9', 'hex').toString() !== '💩'`

**Comment by sidorares** [comment]
`new Buffer('string', enc)` is deprecated - should be `Buffer.from('string', enc)` ( + [safe-buffer](https://github.com/feross/safe-buffer) polyfill )

**Comment by ashtuchkin** [comment]
Hmm, thanks for the info. I still need to support Node v0.10 and would like
to avoid external dependencies.. Is there any other options?

--
Alexander Shtuchkin

**Comment by sidorares** [comment]
I'm afraid only option is to pull safe-buffer content, it's quite small - https://github.com/feross/safe-buffer/blob/master/index.js

**Comment by phated** [comment]
@ashtuchkin I wouldn't worry about the deprecation currently

**Comment by sidorares** [comment]
@chalker how likely is hard deprecation soon?

**Comment by ashtuchkin** [comment]
Ok, so fixed in c7a8243 and published as v0.4.18.

**Comment by ashtuchkin** [comment]
Thanks for the report @sidorares!

**Comment by ChALkeR** [comment]
@sidorares At this moment, there is not ETA for the hard deprecation of `new Buffer`. I.e. at the last discussion of this in March, the CTC decided to not set a timeframe for runtime deprecation at this moment.

That doesn't mean that it can't happen , though. It definitely won't happen before 9.0 (October 2017) and I find it unlikely that it will happen in 9.0 (though personally I would prefer to see that in).

There are other resons why you shouldn't be using the old API, though.

Also note that the `safe-buffer` polyfill is only needed for Node.js versions lower than 4.4.x and lower, 5.x branch, 0.10 branch and 0.12 branch. I don't think that really needed nowdays.

**Comment by ChALkeR** [comment]
@sidorares At this moment, there is no ETA for the hard deprecation of `new Buffer`. I.e. at the last discussion of this in March, the CTC decided to not set a timeframe for runtime deprecation yet.

That doesn't mean that it can't happen , though. It definitely won't happen before 9.0 (October 2017) and I find it unlikely that it will happen in 9.0 (though personally I would prefer to see that in).

There are other resons why you shouldn't be using the old API, though.

Also note that the `safe-buffer` polyfill is only needed for Node.js versions 4.4.x and lower, 5.x branch, 0.10 branch and 0.12 branch. I don't think that really needed nowdays.

**Comment by sidorares** [comment]
@chalker I had 3 bug reports next day after I accidentally released node-mysql2 with one of the functions using new API without shim, there are still plenty of pre node 4.5 users
