### ISSUE TITLE
Encoding name normalization does not remove year suffix

### ISSUE THREAD

**Issue by rossj** [ashtuchkin/iconv-lite#156]
[This line](https://github.com/ashtuchkin/iconv-lite/blob/master/lib/index.js#L68) is supposed to normalize encoding names by removing non-alphanumeric characters and stripping an appended year. The year is not being stripped with the current regex, causing encoding names with years to not match.

Example:
Input: `iso_8859-5:1988`
Output: `iso885951988`
Expected output: `iso88595`

I think the reason the current regex does not work is that the colon character is matched in the first part as a non-alphanumeric character, therefore causing the following year part to not match.

**Comment by erikkemperman** [comment]
Just noticed the same thing. Suggested fix:
```js
.toLowerCase().replace(/:\d{4}$/, "").replace(/[^0-9a-z]/g, "");
```

**Comment by ashtuchkin** [comment]
Thanks guys, I think you're right, I'll add a fix soon.

--
Alexander Shtuchkin

**Comment by erikkemperman** [comment]
Actually, maybe it should be
```js
.toLowerCase().replace(/:\d{4}[^0-9a-z]*$/, "").replace(/[^0-9a-z]/g, "");
```

**Comment by rossj** [comment]
FWIW I just swapped the ORs in my local copy
```javascript
/:\d{4}$|[^0-9a-z]/g
```

**Comment by erikkemperman** [comment]
I was thinking you might want to get rid of trailing (after the year) non-alphanumerics as well?

**Comment by erikkemperman** [comment]
Thanks!
