### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by JsseL** [ashtuchkin/iconv-lite#159]
Readme says:
> ... Works on Windows and in sandboxed environments like Cloud9.

and later
> Comparison with node-iconv module (1000x256kb, on MacBook Pro

which sounds like this might work also on Mac. How is it, is this somehow Windows only (and in sandboxed environments) as the Readme suggests or not?

**Comment by ashtuchkin** [comment]
Yes, both Mac and Linux are definitely supported.

--
Alexander Shtuchkin

**Comment by JsseL** [comment]
Then perhaps some rewording in Readme might make sense, at least for me
> Works on Windows and in sandboxed environments like Cloud9.

was a bit confusing.

But in any case, thanks for the answer and the lib! :+1:
