### ISSUE TITLE
Problem with file after browserifying iconv-lite 

### ISSUE THREAD

**Issue by grath10** [ashtuchkin/iconv-lite#160]
When I use the file after processing with browserify, console inbrowser get this info:
iconv-lite warning: javascript files are loaded not with utf-8 encoding. See https://github.com/ashtuchkin/iconv-lite/wiki/Javascript-source-file-encodings for more info.
And I tried to adopt the suggestion offered in the wiki, the problem still appears.
How to solve this? Appreciate any help available!
To add, the browser is chrome and language is in Chinese.

**Comment by larssn** [comment]
Sounds like you need to save your js files with UTF8 encoding. See https://stackoverflow.com/a/40365121/536485 (requires VSCode)
