### ISSUE TITLE
Untranslatable latin-1 characters no longer converted to ?

### ISSUE THREAD

**Issue by mbloch** [ashtuchkin/iconv-lite#162]
According to the README, "Untranslatable characters are set to � or ?".

This seems no longer to be true for latin-1 (a consequence of switching to using native Node encoding?)

(Upgrading iconv-lite from 0.4.14 to 0.4.18 caused some tests to start failing in one of my projects. For example, encoding  `étranger,外国人` to/from latin-1  produced `étranger,\u0016ýº` instead of the expected `étranger,???`. Testing with several versions of Node on MacOs gave the same result.)

I prefer the original behavior, but if the current behavior is retained, perhaps the README could be updated  :)

**Comment by ashtuchkin** [comment]
Very interesting, thanks for the report! It looks like it was the unexpected consequence of #147. I'll revert that commit.

**Comment by ashtuchkin** [comment]
Okay this should be fixed in febb0b8e280de5de844151036e87cfa06b92d548. I'll publish new iconv version soon. Thanks!
