### ISSUE TITLE
ISO-8859-1 encoding not correct

### ISSUE THREAD

**Issue by tharaka1** [ashtuchkin/iconv-lite#163]
I am working on pass authorization header to encoded text. Server expects ISO-8851-1 encoding format.

Here I used iconv and try to get encoded string and it gives a different encoded string . what can be the reason?

var str  = this.username+':'+this.password;
var s = iconv.encode(str, 'ISO-8859-1');
var a = btoa(s.toString()); 
headers.append('Authorization', 'Basic ' + a);

**Comment by ashtuchkin** [comment]
This line might be the problem:
var a = btoa(s.toString())

"s" here is actually a Buffer with encoded data. When you do .toString(),
you lose the encoding.

Instead, I recommend either of these:
var a = s.toString("base64");
Or
var a = iconv.decode(s, "base64");

Also please make sure to read these wiki pages for more context:
https://github.com/ashtuchkin/iconv-lite/wiki
https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding

**Comment by ashtuchkin** [comment]
To be more specific, buffer.toString() decodes binary data in that buffer
using utf-8 encoding, so that messes up things.

**Comment by tharaka1** [comment]
I have tried both s.toString("base64") and iconv.decode(s, "base64"). but it gives same as btoa(s.toString())

var s = iconv.encode(str, 'ISO-8859-1'); // Is this correct?
I debug the code and check, this is given Unit8Array same as byte array of the string. This look 
like utf-8 encoded array.

**Comment by ashtuchkin** [comment]
Maybe what trips you up is ISO-8859-1 is actually the same as UTF-8 for all
ASCII characters. It's only different in characters with accents etc.

So i.e. iconv.encode("Hello, world!", "ISO-8859-1").toString() should be
equal to "Hello, world!" and it's correct behavior.

Can you provide the values you're testing with and what output values you
expect?


--
Alexander Shtuchkin

**Comment by tharaka1** [comment]
I sent you details of testing and what i am expecting.
