### ISSUE TITLE
support for windows-1252

### ISSUE THREAD

**Issue by idangozlan** [ashtuchkin/iconv-lite#167]
Hi,

Is that possible use this convertor for windows-1252 to utf-8 conversion?

Thanks

**Comment by ashtuchkin** [comment]
Yes.

**Comment by idangozlan** [comment]
Can you please provide example? Didn't find the way..

**Comment by ashtuchkin** [comment]
function convert(buffer_in_win1252_encoding) {
  var str = iconv.decode(buffer_in_win1252_encoding, "windows-1252");
  var output_buffer_in_utf8_encoding = iconv.encode(str, "utf8");
  return output_buffer_in_utf8_encoding;
}

See also wiki in this project for more information.

--
Alexander Shtuchkin

**Comment by idangozlan** [comment]
Well... not working.

**Comment by ashtuchkin** [comment]
Works for me...

--
Alexander Shtuchkin
