### ISSUE TITLE
Error: Encoding not recognized: 'cp720' with Persian as system language

### ISSUE THREAD

**Issue by fttx** [ashtuchkin/iconv-lite#168]
Lately, some users are reporting this error when they open my electron app.
The system language, in this case, was set to Persian:

<img width="1280" alt="screen shot 1396-08-24 at 20 24 53" src="https://user-images.githubusercontent.com/5663423/32851723-18477744-ca36-11e7-82aa-3ca74263f849.png">

**Comment by ashtuchkin** [comment]
Looks like cp720 is rather rare encoding and not supported by iconv library (from which I got the list of encodings). Would you want to add a pull request to add it? See cp808 as an example how it could look like: https://github.com/ashtuchkin/iconv-lite/blob/master/encodings/sbcs-data.js#L15
