### ISSUE TITLE
utf8 to windows1255 string

### ISSUE THREAD

**Issue by LionOpeter** [ashtuchkin/iconv-lite#170]
Hello,
I've been trying to convert from utf8 string to windows-1255 string for along time now.
I came up with this code:
```
var fs = require('fs');
var Iconv = require('iconv').Iconv;
var iconvlite = require('iconv-lite');
var windows1255 = require('windows-1255');

/////////////////// Attempting to converted from utf-8 to windows-1255
function encode(content) {
  var iconv = new Iconv('UTF-8', 'CP1255//TRANSLIT//IGNORE');
  var buffer2 = iconv.convert(content);
  return buffer2;
  //return buffer.toString('ISO-88591-1');		// toString cannot convert in the encoding windows1255
};
var buffer3 = new Buffer(encode(fs.readFileSync('/home/USER/git/npm-test-1/utf8.txt')));
console.log(buffer3);
//str = iconvlite.decode(buffer3, 'win1255');
str = iconvlite.decode(buffer3, "1255");
console.log(str);


fs.writeFile("/home/USER/git/npm-test-1/windows-1255.txt", str, function(err) {
    if(err) {
        return console.log(err);
    }

    console.log("The file was saved!");
}); 
```
Only problem is on the last step, when I'm trying to convert from a buffer to a string.
It converts it alright but to a utf8 encoding string :|
1. Is this a bug?
2. Is there any way around this? I really need windows-1255 string and not a buffer.
3. Anyone knows a way to do this?

**Comment by ashtuchkin** [comment]
Hey, there's several things going on here:
 1. Using `str = iconvlite.decode(buffer3, "1255");`, you're converting from a win1255-encoded buffer to a JS string. JS string doesn't have encoding, it's just a list of characters.
 2. When you do `console.log(str)`, the string is converted to whatever encoding your terminal has and shows you the characters.
 3. When you do `fs.writeFile("...", str, ..)`, Node writes JS string to the file using default encoding, which is utf-8.

If you want to save that string in win1255 encoding, just write the `buffer3` directly:
`fs.writeFile("/home/USER/git/npm-test-1/windows-1255.txt", buffer3, ..`

See more info in my wiki: https://github.com/ashtuchkin/iconv-lite/wiki and https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding

**Comment by LionOpeter** [comment]
Hi @ashtuchkin and thank you very much for replying.
I get what you said. My main goal (as i mentioned in my question number 2) is to create a string which has the right character(s). For me the right characters are the characters of windows-1255 encoding because my IRC server works only with this charset.If i send the server the wrong encoding i get an error saying `'Nickname is unavailable: Illegal characters'` Any idea how i can pull this off?

**Comment by ashtuchkin** [comment]
I see. Can you send a buffer (i.e. actual bytes) to that server? that would
be the simple solution. If you can only send strings, then you'll need to
determine where exactly encoding conversion is happening. As I said, JS
strings don't have encodings by themselves - it's a list of characters, not
bytes.

Sometimes legacy code do use strings as lists of bytes, though. If you have
this case, then you might try using `str = buffer3.toString("binary")`.
That might or might not work.


--
Alexander Shtuchkin

**Comment by LionOpeter** [comment]
If i try to send it as a buffer i get error:
```
/home/USER/git/npm-test-1/node_modules/irc/lib/irc.js:930
    if (args[args.length - 1].match(/\s/) || args[args.length - 1].match(/^:/) || args[args.length - 1] === '') {
                              ^

TypeError: args[(args.length - 1)].match is not a function
    at Client.send (/home/USER/git/npm-test-1/node_modules/irc/lib/irc.js:930:31)
    at Client._connectionHandler (/home/USER/git/npm-test-1/node_modules/irc/lib/irc.js:725:10)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1125:10)

```
In-addition, an attempt to use `str = buffer3.toString("binary")` ended up with the same result of `Illegal characters` error. Any way to assign a string with a hex value in javascript?

**Comment by ashtuchkin** [comment]
Nah, this problem need to be resolved on the irc module side. I noticed
there's an "encoding" option for irc client (
https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L59), maybe
you set that to "windows-1255" and just send the strings?

If you still want to experiment with manual character manipulation in
strings, you can look here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode

--
Alexander Shtuchkin
