### ISSUE TITLE
Anti malware from GOTMLS.NET found a known threat

### ISSUE THREAD

**Issue by totanus** [ashtuchkin/iconv-lite#172]
Hello,
I'm in a team developing a custom WordPress theme using also the iconv-lite node module.
When scanning the theme against known threats with the "Anti-Malware from GOTMLS.NET" plugin the resulting report says that file gbkFile.txt in "/node_modules/iconv-lite/test/" is a known threat.
As I can see this is just a txt file containing a Baidu related HTML page.
As I can see this file is also contained in the actual repository, so I'm going to ask you for confirmation that it is a legit file.
Thank you in advance for your support.
Matteo

**Comment by ashtuchkin** [comment]
It's a snapshot of baidu main page, used only for testing. You can delete
the /test directory, not sure why it's even published, it's in my
.npmignore file.

--
Alexander Shtuchkin
