### ISSUE TITLE
One last "new Buffer" usage in lib

### ISSUE THREAD

**Issue by dougwilson** [ashtuchkin/iconv-lite#184]
I got a report at https://github.com/stream-utils/raw-body/issues/59#issuecomment-387082903 that says there is still one `new Buffer` usage remaining in the module when `require('iconv-lite')` is called:

https://github.com/ashtuchkin/iconv-lite/blob/master/lib/extend-node.js#L13

I will look today to come up with a patch, but opening an issue in case someone wants to beat me too it 👍

**Comment by felixbuenemann** [comment]
I'm working on a PR to fix this right now.
