### ISSUE TITLE
Unicode character problem

### ISSUE THREAD

**Issue by SombraRO** [ashtuchkin/iconv-lite#187]
Every message that uses the character `ç` next to another Unicode returns a strange character.

**Using encode: UTF-8**

**Comment by ashtuchkin** [comment]
```
> iconv.encode("çã", "utf8")
<Buffer c3 a7 c3 a3>
> iconv.encode("çã", "utf8").toString()
'çã'
```

Can you write a code snippet that shows your problem?

Also, make sure you read https://github.com/ashtuchkin/iconv-lite/wiki
