### ISSUE TITLE
Breaking change released as patch version 0.4.20

### ISSUE THREAD

**Issue by cif** [ashtuchkin/iconv-lite#193]
This is a breaking change released as a patch version: 
https://github.com/ashtuchkin/iconv-lite/blob/master/Changelog.md#0420--2018-04-06

Unfortunately, since iconv-lite was a third party depencency, this change took out our lambdas for half a day. The solution (not the easiest to find or deploy) was to pin this module to the version before it in our top level package.json

I realize this lib is still is not at version 1 and exempt from semver but... I need to say something because we, as a community of NodeJS developers absolutely get the most heat from the broader developer community for releasing breaking changes in minor versions with an unfortunate ^ syntax defaulted into our package manager : ) 

At this time, iconv-lite has 6.6 million downloads per day, perhaps it's time to make version 1 now that it has that kind of reach?

Thank you for your consideration!

**Comment by cif** [comment]
Looks like someone else suggested this as well https://github.com/ashtuchkin/iconv-lite/issues/132

**Comment by ashtuchkin** [comment]
Thanks for the feedback, Ben!

I do agree with you in general, but I don't see how in this particular case
it would've helped.. it wasn't an API change, the problem was in adding a
dependency that didn't work in some environments. I might be missing
something, but I'd classify this change as patch-level change in semver
too. Am I wrong about this?

Alex

**Comment by cif** [comment]
Hey Alex, 

First of all, thanks for the quick response and all your hard work on this library! It's really awesome that so many folks are finding it useful.

I had an interesting Slack conversation today within my organization about semver and dependency management with Node in general. 

Newer npm tooling like package-lock.json and yarn.lock makes things "better" in that we can (and should!) pretty easily lock the entire depedency tree down, so that semver becomes less of an issue (arguably irrelevant). 

Most of the folks here are seem to agree that as a developer you are responsible for making sure breaking changes don't find their way into your code via these new tools, unfortunately, the npm defaults are still subseptible to breaking changes. 

Regarding the specific changes to your code, Changes to the buffer contructors here: 
https://github.com/ashtuchkin/iconv-lite/commit/59314034f2bb1a1d622023d8acfec64961629364 e.g `new Buffer` vs `Buffer.from` and `Buffer.alloc` are ultimately what caused an issue with our depenent module.  

Here's the stack trace for reference:
```
Unable to import module 'functions/updateTranslations/handler': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/node_modules/iconv-lite/lib/index.js:5:14)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
```

The npm repo was older and not using the "saftey net" tooling mentioned above. 

Ultimately it is up to you to adopt what appoaoch you like, though the fact remains that a major change, publishing the buffers after would have prevented a break in our case.

Feel free to close this issue, it was strictly for your visibility. 
Thanks again!
🍻 
Ben

**Comment by cif** [comment]
I also just dug a bit deeper into that commit - seems like a polyfill was added to support backward compatibility?  

Further, you also make a pretty interesting point regarding API vs environmental factors and semver, to which I answer 🤷‍♂️   

Lesson of the day seems to be: lock down your dependencies soon as you're in production when using NodeJS - no expcetions 😄
