### ISSUE TITLE
Remove Buffer constructor from tests

### ISSUE THREAD

**Issue by gabrielschulhof** [ashtuchkin/iconv-lite#197]
The `Buffer` constructor is deprecated and unsafe. Is it possible to switch to `Buffer.from(...)` in the tests, where the [last remaining instances](https://github.com/ashtuchkin/iconv-lite/search?p=1&q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22) occur?

**Comment by ashtuchkin** [comment]
Sure! Care to do a pull request?

**Comment by ashtuchkin** [comment]
Fixed in ef662384edbdc2a5e0682ff989688d1e3885992a
