### ISSUE TITLE
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues.

### ISSUE THREAD

**Issue by FL0RIANMEYER** [ashtuchkin/iconv-lite#200]
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

at **extend-node.js**

Node 10.7.0

**Comment by ashtuchkin** [comment]
This is on purpose.

**Comment by martpie** [comment]
I am not sure to understand the "This is on purpose" here. does it mean this library won't work with future version of Node.js when `Buffer()` will be removed?

**Comment by ashtuchkin** [comment]
It will work. Buffer() won't be called if `Buffer.from` exists. The code is here: https://github.com/ashtuchkin/iconv-lite/blob/master/lib/extend-node.js#L13
