### ISSUE TITLE
ISO-8859-12 is missing

### ISSUE THREAD

**Issue by OddMorning** [ashtuchkin/iconv-lite#208]
I was checking every encoding that [wiki](https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings) has and it turned out that `iconv.encodingExists('ISO-8859-12') === false` while ISO-8859-1 - ISO-8859-11 and ISO-8859-13 - ISO-8859-16 still exist

**Comment by ashtuchkin** [comment]
yeah because there's no ISO-8859-12 standard :)
https://en.wikipedia.org/wiki/ISO/IEC_8859-12

**Comment by OddMorning** [comment]
Oh, I didn't know that. Should the line in wiki be changed to something like `ISO codepages: ISO-8859-1 - ISO-8859-16 (except for ISO-8859-12)` then? Or is it too silly to mention (like it's well known exception among people who works a lot with encodings)?

**Comment by OddMorning** [comment]
I never went further than 437, 866, utf8, and utf16, so I didn't know about such details, my bad.
