### ISSUE TITLE
Licence file is missing MIT header

### ISSUE THREAD

**Issue by BorisUK** [ashtuchkin/iconv-lite#211]
Please add the "The MIT License (MIT)" header into the licence file: https://github.com/ashtuchkin/iconv-lite/blob/master/LICENSE

**Comment by ashtuchkin** [comment]
What I have in LICENSE file is the common form of this license. It specifically does not include the header you're suggesting. If a developer is not sure which license is that, I think these clues should help:

![image](https://user-images.githubusercontent.com/627997/50730231-9e0b3c80-1116-11e9-876e-57ad4747e6dd.png)
--------
![image](https://user-images.githubusercontent.com/627997/50730239-c72bcd00-1116-11e9-962f-20f4aec02887.png)
--------
![image](https://user-images.githubusercontent.com/627997/50730223-63a19f80-1116-11e9-93d8-72bf6dd92bde.png)
