### ISSUE TITLE
How can this library be used in an isomorphic lib

### ISSUE THREAD

**Issue by jacktuck** [ashtuchkin/iconv-lite#212]
So i created a scraping library [ unfurl ](https://github.com/jacktuck/unfurl) which uses iconv-lite to convert to utf-8. This library (iconv-lite) works great for our indented use case, Node. But we need to support browsers now too. Is there anyway I can use this library without having to make two builds (one for node, one for browser)?

https://www.npmjs.com/package/cross-fetch seems to be isomorphic and does not require different builds.

**Comment by jacktuck** [comment]
I'm not sure why but everything seems to work if i export the decode method rather than reference it

Works in Node.js & Browser
```
import { decode } from 'iconv-lite'
decode(...)
```

Works in Node.js only
```
import iconv from 'iconv-lite'
iconv.decode(...)
```

**Comment by ashtuchkin** [comment]
Yes it should work with e.g. browserify. Be advised though that the encoding tables might increase the size significantly (tens-hundreds of kb, depending on serving configuration).
