### ISSUE TITLE
Any possible to encode Arabic text please help me.

### ISSUE THREAD

**Issue by FazilMuhammed** [ashtuchkin/iconv-lite#225]

**Comment by ashtuchkin** [comment]
iconv-lite does support [Windows-1256](https://en.wikipedia.org/wiki/Windows-1256) codepage if that's what you mean.

**Comment by FazilMuhammed** [comment]
@ashtuchkin then how can print Arabic text any suggestion

**Comment by ashtuchkin** [comment]
iconv-lite can't help you with printing - it's just converting from/to encodings. Please see examples in readme. Just use "windows1256" or "utf8" as encoding name, depending on what you're using.
