### ISSUE TITLE
Encoding win1251

### ISSUE THREAD

**Issue by themrxcm** [ashtuchkin/iconv-lite#233]
Hi! Tell me, please, is it possible to translate from windows-1251 to utf-8 such JSON
`TEST": {
    "CODE": 1,
    "NAME": "����",
  },`
The Atom text editor uses your package and they can do it, but I couldn't find an implementation in their code. Thanks! Sorry for my bad English.

**Comment by ashtuchkin** [comment]
Both win1251 and utf8 are supported in iconv-lite. To convert binary data
in win1251 encoding to a js string, use iconv.decode(bug, "win1251"). To
convert js string to utf8 data, either use iconv.encode(str, "utf8"), or
just use the string directly (utf8 is the default encoding and node.js will
convert it for you)

**Comment by themrxcm** [comment]
My example:
`
 let str = iconv.decode(buff, "windows-1251");
 let utf8 = iconv.encode(str, "utf8");
 console.log(utf8.toString())
`
In console: 
`
  "TEST": {
    "CODE": 1,
    "NAME": "пїЅпїЅпїЅпїЅ",
  }
`
It should be: 
`
"TEST": {
    "CODE": 1,
    "NAME": "Тест", // Russian language
  }
`

**Comment by ashtuchkin** [comment]
Also note that you likely need to decode data before parsing json. If you
have already parsed it, it's too late to do decoding.

**Comment by ashtuchkin** [comment]
In your example you're encoding utf8 twice. Once using iconv-lite, second
time when you do buf.toString(). Try console.log(str)?

**Comment by themrxcm** [comment]
Yes, you are right! I may need to specify the encoding when using `fs.readFile()`. But of all the possible options there is no suitable one for me ):
I will look for a solution further. The problem appears earlier, but your package is working correctly

console.log(str)
`"TEST": { "CODE": 1, "NAME": "пїЅпїЅпїЅпїЅ", }`

As I find a solution I will write a comment

Thanks!

**Comment by themrxcm** [comment]
Sorry, my inattention failed me. I converted a corrupted file that had a wrong encoding. If you need an example here it is:

```
const autoenc = require('node-autodetect-utf8-cp1251-cp866');
const fs = require('fs');
const Buffer = require('buffer').Buffer;
const iconv = require('iconv-lite');

convert('./test.json')

function convert(path) {
  const data = fs.readFileSync(path);
  let buff = new Buffer.from(data);
  const encoding = autoenc.detectEncoding(buff).encoding
  let str = iconv.decode(buff, encoding || 'utf8');
  let utf8 = iconv.encode(str, "utf8");
  fs.writeFileSync('./testw.json', utf8)
  return utf8;
}
```
Your suggestion about re encoding helped me a lot! Thanks!

**Comment by ashtuchkin** [comment]
Awesome, glad you resolved the issue!
