### ISSUE TITLE
Wavy line is not correctly in EUC-JP

### ISSUE THREAD

**Issue by ylsxch** [ashtuchkin/iconv-lite#234]
There are two "～" in eucjp.json. Both "a1c1" and "8fa2b7" mapped to "～".
Should it be modified as follows：

**before :** 
```
 ["8fa2af","˘ˇ¸˙˝¯˛˚～΄΅"],
```
**after :**
```
["8fa2af","˘ˇ¸˙˝¯˛˚"],
["8fa2b8","΄΅"],
```
Thanks.

**Comment by ashtuchkin** [comment]
Hey, I'm using [WHATWG Encoding Standard](http://encoding.spec.whatwg.org/) as the source of these tables, see [index-jis0212.txt](https://encoding.spec.whatwg.org/#index-jis0212) and [index-jis0208.txt](https://encoding.spec.whatwg.org/#index-jis0208) there. By that standard both a1c1 and 8fa2b7 byte sequences should be decoded as "～".

You can try it for example in Chrome DevTools console:
```
let dec = new TextDecoder("euc-jp");
console.log(dec.decode(Uint8Array.from([0xa1, 0xc1])));
console.log(dec.decode(Uint8Array.from([0x8f, 0xa2, 0xb7])));
```

Does this cause you any problems?

**Comment by ylsxch** [comment]
Yeah, I think you are right.
If I want to get “a1c1” instead of “8fa2b7”, what should I do？
`new_string = iconv.encode("～", "eucjp");  // I get "8fa2b7" by this code`
Thanks.

**Comment by ashtuchkin** [comment]
"8fa2b7" is what Encoding Standard returns in this case, so it doesn't make sense to change the default behavior. In your particular application you can do the following to make it return "a1c1":
```
var iconv = require("iconv-lite");
iconv.encodingExists(""); // preload encodings.
iconv.encodings["eucjp"].encodeSkipVals = [0x8fa2b7];

// then
buf = iconv.encode("～", "eucjp");  // returns <Buffer a1 c1>
```

**Comment by ylsxch** [comment]
OK, thanks a lot !
I will close this issue.
