### ISSUE TITLE
Cannot find module 'iconv-lite' or its corresponding type declarations

### ISSUE THREAD

**Issue by dogtopus** [ashtuchkin/iconv-lite#248]
Both Eclipse WWD and VSCode complain about missing TypeScript declarations if I import the library with `import iconv from 'iconv-lite'` and falling back to `var iconv = require('iconv-lite')` works fine (but without any typing of course). Installing the now deprecated `@types/iconv-lite` makes the error go away.

**Comment by ashtuchkin** [comment]
Can you try importing it like this:
```
import * as iconv from 'iconv-lite'
```

**Comment by dogtopus** [comment]
Tried that as well. Still didn't work.

**Comment by dogtopus** [comment]
I accidentally fixed it by setting `moduleResolution` to `node`. Leaving this option unset didn't cause any problem before probably due to the fact that the code I'm working on is not intended to be ran on NodeJS.
