### ISSUE TITLE
Decoding cp862 produces reversed string

### ISSUE THREAD

**Issue by igorthy** [ashtuchkin/iconv-lite#252]
Hi,

I'm decoding text file encoded with **cp862/ibm862** (hebrew codepage) and encoding it back to **utf8**.
For some reason the utf8 strings are reversed.
I can fix it using **esrever** library with its **reverse** method but it feels not right :/

Any idea why this might be happening ?

Thank you

**Comment by ashtuchkin** [comment]
Hard to say; the codec definitely doesn't do any reversals. Care to post a code example? Maybe the strings are shown in reverse in your console/editor/IDE due to an RTL character? I don't know much about it though.

**Comment by igorthy** [comment]
Here you go:

[pricelist.txt](https://github.com/ashtuchkin/iconv-lite/files/4879581/pricelist.txt)

**Comment by ashtuchkin** [comment]
Nice, thank you! Could you also post the code you're using, what it prints and what you expect it to print? Or, ideally, an assert that fails.

To be clear, there's very little chance the reversal happens inside `iconv-lite` - there's just no code inside to do it. It's very likely the reversal happens either before or after.

**Comment by igorthy** [comment]
You can test it simply by doing:
```
import  * as mississippi from 'mississippi-promise';
import {createReadStream, createWriteStream} from 'fs';
import {decodeStream, encodeStream} from 'iconv-lite';

mississippi.pipe(
createReadStream(src),
decodeStream("ibm862"),
encodeStream('utf8'),
createWriteStream(dst)
).then(()=>console.log('done'));
```

**Comment by ashtuchkin** [comment]
Ok, let's check what we should expect.
```js
// read source file in binary mode; it's rather big: 356 kb.
var buf = fs.readFileSync("pricelist.txt");  

// Extract one line as a string in binary encoding; let's take the 5th one as an example, to avoid headers, etc.
var lines = buf.toString("binary").split("\r\n");
var line = lines[4];
console.log(line);  // we see some numbers separated by lots of spaces, then weird symbols. 

// Let's get rid of the spaces and extract columns
var columns = line.split(/ +/).filter(Boolean);
console.log(columns);  // => ['0', '2', '7', '0', '0', '0.00', '0.00', '',  '']   // first 7 columns are numbers, then some space-separated characters.

// Try to decode the characters manually using https://en.wikipedia.org/wiki/Code_page_862
console.log(Buffer.from(columns.slice(7).join(' '), "binary"));
// => <Buffer 8f 81 80 20 9a 85 83 85 81 92>

// Note, we have 3 character word, then space, then 5 character word.
var decodedChars = [
 /* 8f */ 'ן',
 /* 81 */ 'ב',
 /* 80 */ 'א',
 /* 20 */ ' ',
 /* 9a */ 'ת',
 /* 85 */ 'ו',
 /* 83 */ 'ד',
 /* 85 */ 'ו',
 /* 81 */ 'ב',
 /* 92 */ 'ע'
];

// Now try to join them into a single string:
var decodedStr = decodedChars.join('');
console.log(decodedStr); // => 'ןבא תודובע'   // Note this is printed in reverse by the browser (try to copy-paste it somewhere and move text cursor using left and right arrows)

// Decoded string above is printed in reverse in the browser and console, although the order of characters is still the same:
console.log(decodedStr[0]);  // => 'ן'
console.log(decodedStr[1]);  // => 'ב'
...
```

Okay, so what iconv-lite is producing?
```
var buf = fs.readFileSync("pricelist.txt");
var lines = iconv.decode(buf, "cp862").split('\r\n').replace("  ", " ");
console.log(lines[4].replace(/ +/g, " ")) // => ' 0 2 7 0 0 0.00 0.00 ןבא תודובע'
```
Looks exactly the same as what we have manually decoded above.

So, ultimately the reversion happens when you output the strings either to the console or to the browser. See https://en.wikipedia.org/wiki/Bidirectional_text for more info.

Let me know if you have any more questions!
