### ISSUE TITLE
Any posible to encode Arabic Text

### ISSUE THREAD

**Issue by FazilMuhammed** [ashtuchkin/iconv-lite#254]
Anyone Knows Please help me :)

**Comment by ashtuchkin** [comment]
There are several Arabic encodings supported, what exactly do you need?

**Comment by FazilMuhammed** [comment]
@ashtuchkin can you suggest anyone.i'm using iconv-lite to encode. I try utf8 , win125 but cannot print Arabic text properly is there any solution to print Arabic text properly. please help me I lost couple of weeks behind this.

**Comment by ashtuchkin** [comment]
Ok, could you answer each of these these questions please:
 1. What operating system do you use? Can you see this string in arabic -> `اللغة العربية`?
 2. Where are you getting your Arabic text from? Is it generated by your program or some external resource (like a website or a text file)? If you can share it, please copy-paste a short sample of it here or attach a file.
 3. Do you know what encoding is used in that source? Utf8? [Win1256](https://en.wikipedia.org/wiki/Windows-1256)? Something else?
 4. Where exactly are you trying to print the Arabic text? Is it a website, console, something else? Please describe.
 5. How are you trying to print Arabic text there? Please copy-paste the code you use.
 6. What have you tried to do already? Did you get to the point where you see arabic characters or not?

**Comment by FazilMuhammed** [comment]
@ashtuchkin Thanks for your response

I'm a react native developer. I need print Arabic Text in payment slip so with help of this library react Native Bluetooth serial next (https://github.com/nuttawutmalee/react-native-bluetooth-serial-next) I can print English text easily but I cannot print Arabic text properly. this is my Bluetooth thermal printer(https://www.amazon.com/Portable-Thermal-Printer-Wireless-Bluetooth/dp/B075VKXBJW). Arabic text are static i generated program 
when I connection between Bluetooth device and my phone success after I send my text and messages to this function 

I cannot send message directly printer device after encode then only Its works
 
first of I import the 

var iconv = require("iconv-lite");

 to my project.

 writePackets = async (id, message, packetSize = 64) => {
    let toWrite;
    try {
      const device = BluetoothSerial.device(id);

      toWrite = iconv.encode(message, "win1251");

      const writePromises = [];
      const packetCount = Math.ceil(toWrite.length / packetSize);

      for (var i = 0; i < packetCount; i++) {
        const packet = new Buffer(packetSize);
        packet.fill(" ");
        toWrite.copy(packet, 0, i * packetSize, (i + 1) * packetSize);
        writePromises.push(device.write(packet));
      }

      await Promise.all(writePromises).then(() =>
        Toast.showShortBottom("Writed packets")
      );
    } catch (e) {
      Toast.showShortBottom(e.message);
    }
  };
English text is already printing. Cannot print other language mainly Arabic text if you please help me ;)

**Comment by ashtuchkin** [comment]
You probably need to switch encoding of the printer itself. Have you seen
https://stackoverflow.com/a/61836924/325300 ? Try sending these bytes and
then encoded string. Use "cp864" as encoding for iconv-lite.

**Comment by ashtuchkin** [comment]
Looks like there's someone reporting success using similar method:
https://github.com/song940/node-escpos/issues/136#issuecomment-401030947

The encoding number will be different (see linked PDF file for list), but
overall approach looks feasible.

**Comment by ashtuchkin** [comment]
@FazilMuhammed was it helpful?

**Comment by SayedBazarah** [comment]
same problem, I can not print Arabic characters

**Comment by ashtuchkin** [comment]
I'm sorry you have a problem @SayedBazarah, but it's hard for me to help you without any details. If you think iconv-lite has a bug, please provide minimal reproduction and what you've already tried, ideally in a new issue (as this one is closed).

**Comment by SayedBazarah** [comment]
@ashtuchkin  Hey
 
I use React Native Bluetooth Escpos Printer
https://github.com/januslo/react-native-bluetooth-escpos-printer

I don't know how to encoding the Arabic text to the printer, the printer always print Arabic word as ????? 

await  BluetoothEscposPrinter.printText("رقم الفاتورة：0.00",{
 encoding:'GBK', //Default encoding
  codepage:0, //For English 
  widthtimes:0,
  heigthtimes:0,
  fonttype:1
});

**Comment by ashtuchkin** [comment]
This snippet doesn't contain any iconv-lite references, have you tried getting support in that BluetoothEscPos library? You can use a static string encoded with GBK for your tests.
When that works, you can convert a utf8/utf16 string to GBK using iconv-lite.
