### ISSUE TITLE
How to determine the character-set to be decode

### ISSUE THREAD

**Issue by kajweb** [ashtuchkin/iconv-lite#259]
1、I use `http.request` to request a web page  
2、pipe(through2( `someFunction( chuck, enc, cb )` )  
3、however，in someFunction `chuck` is Buffer。I want to turn it into String，but I don’t know how to choose Characters-Set to decode.  
- The encryption method of different websites may be different, some use UTF-8, GB2312 or win1251.  
- The most important thing is that the content-type in the response headers does not carry charset  

Such as, [baidu zhidao](https://zhidao.baidu.com)is written by gb2312。But when crawling, I don’t know the content of the webpage is gb312. I need to convert Buffer to String. But I failed because the program does not know that is using gb2312.

If I use gb2312 by default, but some websites are written in utf-8, they are not compatible.

#42 #53 

```js
pRes.pipe(through2(Core.pipeIconv))

function pipeIconv( chunk, enc, cb ){
	// I want to get the Buffer's(chunk) encoding as a variable
	// cSet = iconv.getCharactersSet(chunk);
	// 	let data = iconv.decode( chunk, cSet );
	let data = iconv.decode( chunk, 'gb2312' );
	// A function to handle strings
	let newString = stopDebugger( data );
	let newBuff = iconv.encode( newString, 'gb2312' );
	// Return Buffer
	cb( null, newBuff );
}
```

**Comment by ashtuchkin** [comment]
Yeah iconv-lite can't help you with that. You'll need to somehow get the encoding first. Maybe there are some other modules that can do that?
