### ISSUE TITLE
No matter how it is used, the parsing is garbled. And the document can still be viewed

### ISSUE THREAD

**Issue by snoopy83101** [ashtuchkin/iconv-lite#261]
help！
This PDF document (China's general invoice) can be viewed, but it is always garbled when parsed.
Can you help me?

![image](https://user-images.githubusercontent.com/24613784/99870291-fd8c6b80-2c0c-11eb-9897-f098c9dbaab0.png)
![image](https://user-images.githubusercontent.com/24613784/99870300-0d0bb480-2c0d-11eb-9f95-80ab6d8e42f2.png)

[zzz.pdf](https://github.com/ashtuchkin/iconv-lite/files/5577185/zzz.pdf)

**Comment by ashtuchkin** [comment]
not sure how I can help. You seem to be using iconv-lite correctly, maybe something with the pdf parser library?

**Comment by snoopy83101** [comment]
Perhaps the problem is with the PDF parser, but unfortunately, the PDF parser does not parse all PDFs. About 50% of Chinese invoices cannot be parsed by a PDF parser.
So I can only use PDF2IMG and then OCR, so I don’t need to consider the text encoding.
