### ISSUE TITLE
Cloud9 no longer exists

### ISSUE THREAD

**Issue by LoganDark** [ashtuchkin/iconv-lite#268]
For a number of years now, Cloud9 (https://c9.io) has no longer existed.

The company sold out to Amazon, who promptly took down Cloud9, assimilated all the code into their offering, and repurposed it to be Amazon-only.

You should probably remove the link from your README. Or update it to the new "AWS Cloud9".

**Comment by ashtuchkin** [comment]
Makes sense, updated, thank you!
