### ISSUE TITLE
test/webpack can't run

### ISSUE THREAD

**Issue by yosion-p** [ashtuchkin/iconv-lite#281]
I'm not sure if this is a problem. If not, I'll close it as soon as possible.
When I refactored the entire project into ESM and tried to run all the test cases, I discovered this phenomenon.
**describe:** test/webpack can't run on my bash.If it only runs on CI, I can't test it locally.
**Runtime env:** git.bash on Windows.
**Steps:** 
```
1. cd to './test/webpack'
2. run 'npm i'
```
then...
![image](https://user-images.githubusercontent.com/86145334/132932341-54cad4ff-23e4-4faa-93d5-080d5595ec11.png)
but,when i run `preinstall` or `mv $(npm pack -pq ../../) iconv-lite.tgz`,they will not be the same:
![image](https://user-images.githubusercontent.com/86145334/132932500-05c712c1-b7b8-4f53-9db3-365eb2d3f977.png)
It is valid, it will generate a new file named `iconv-lite.tgz`.

**Comment by ashtuchkin** [comment]
My guess is bash on windows does not support the $(..command..) notation
which I use in the mv command that is mentioned in the error message. I've
only tested it on linux.
