### ISSUE TITLE
[EUC-JP] U+4FFF(俿) is encoded to IBM拡張文字(8FB1C8) instead of EUC-JP(F9BB)

### ISSUE THREAD

**Issue by mercury233** [ashtuchkin/iconv-lite#285]
```javascript
var iconvLite = require("iconv-lite")
const theChar = String.fromCharCode(0x4FFF);
const theEncodeResult = iconvLite.encode(theChar, 'EUC-JP');
const theDecodeResult1 = iconvLite.decode(Buffer.from([0x8F, 0xB1, 0xC8]), 'EUC-JP');
const theDecodeResult2 = iconvLite.decode(Buffer.from([0xF9, 0xBB]), 'EUC-JP');

console.log(theChar);
console.log(theEncodeResult);
console.log(theDecodeResult1);
console.log('------');
console.log(theDecodeResult2);
console.log(theDecodeResult1 === theDecodeResult2);
```
![image](https://user-images.githubusercontent.com/13391795/138832161-5731d959-846d-4819-9e70-3aa42e9575ad.png)

https://runkit.com/mercury233/6177adadef03d40008209995

As you can see, both 8FB1C8 and F9BB can be decoded, but it can't be encoded correctly.

**Comment by ashtuchkin** [comment]
Well, honestly, I don't know much about EUC-JP either :) Current behavior seems reasonable, so I'm not sure what to do here. Let me know if you learn anything more specific (ideally with a link to some kind of standard), I can then reopen the issue. Thanks!
