### ISSUE TITLE
Supported Encodings: Update Wiki Page

### ISSUE THREAD

**Issue by eekboom** [ashtuchkin/iconv-lite#288]
It seems that the Wiki page at https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings is out of date.
For example these seem to work, but are not included in the list:

Windows-874, UTF-32, UCS-4

Probably there are more.
Or did I miss the info somehow?

**Comment by ashtuchkin** [comment]
Updated the page. Windows-874 was there (see Windows codepages: 874, ...); UTF-32/UCS-4 and a couple more were added. Thank you for noticing!
