### ISSUE TITLE
How to stop iconv-lite from automatically console.log the entire document

### ISSUE THREAD

**Issue by dxcqcv** [ashtuchkin/iconv-lite#314]
The `node.js` print all csv content in terminal when I run following code, I do not know why and how do I to fix it, I do not wanna `console.log` anything, and my code does not have `console.log` command, why does it print file content? help

    const fs = require('fs')
    const path = require('path')
    const iconv = require('iconv-lite');

    const xlsxFilePath = path.resolve(__dirname, './csv/demo.csv')
    
    const fileBuffer = fs.readFileSync(xlsxFilePath );
    const encodedData = iconv.decode(fileBuffer, 'GBK');
    fs.createReadStream(encodedData )

**Comment by ashtuchkin** [comment]
iconv-lite does not print anything anywhere either. Can it be that `fs.createReadStream(encodedData)` is used incorrectly? It accepts file path as the first argument.

**Comment by dxcqcv** [comment]
You're right, my bad, `iconv.decode(fileBuffer, 'GBK');` return string not path, thx
