### ISSUE TITLE
CP737 encoding for Greek

### ISSUE THREAD

**Issue by TakisAmigo** [ashtuchkin/iconv-lite#315]
Hello,

I've seen that IBM-737 is supported in the following page:
https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings

But in the "Reopen with Endoding" command the CP 737 is missing.

This can be considered ( ASCII/DOS Local Codepage )

Is there any workaround that? 
Thanks! Keep up the good work!!

**Comment by ashtuchkin** [comment]
Hello! I'm not sure which application you're talking about when you're mentioning "Reopen with encoding" command? You should probably ask them about it, as iconv-lite is just a library and it does support [CP-737](https://github.com/ashtuchkin/iconv-lite/blob/master/encodings/sbcs-data-generated.js#L197).

**Comment by TakisAmigo** [comment]
Ooops! I thought it was for visual studio code! :)
