### ISSUE TITLE
Unexpected stop when doing many consecutive decodings

### ISSUE THREAD

**Issue by arikw** [ashtuchkin/iconv-lite#79]
Hello,

I'm experiencing the following issue -

I'm using iconv-lite like this:
var iconv = require('iconv-lite');
iconv.decode(buf, 'utf-8'); // "buf" is a buffer ~300KB of size.

If I'm doing as follows multiple times, node just stops with no error:
iconv.decode(buf, 'utf-8');
iconv.decode(buf, 'utf-8');
iconv.decode(buf, 'utf-8');
// ... (x12 times)
iconv.decode(buf, 'utf-8');

Thank you.

**Comment by arikw** [comment]
node v0.10.21

**Comment by ashtuchkin** [comment]
Ok, then try to:
 1. Upgrade node to latest 0.10 and recheck.
 2. Replace all `iconv.decode(buf, 'utf-8')` with `buf.toString('utf8')` - is it still crashing?
