### ISSUE TITLE
bad encoding names in generated data

### ISSUE THREAD

**Issue by mscdex** [ashtuchkin/iconv-lite#86]
Since `iconv.getCodec()` strips all non-alphanumeric characters from the passed in encoding name, it does not find some encodings that currently contain non-alphanumeric characters in the generated encoding data. For example, these single byte encodings: `ansix3.4`, `ansix3.41968`, `ansix3.41986`, `iso646.irv`, `tis620.25291`, `tis620.25330`.

**Comment by ashtuchkin** [comment]
Released a 0.4.6 with a fix for it. Thank you!
It was easier just to remove the dots in alias-defining file.
