### ISSUE TITLE
Create simple method `convert`

### ISSUE THREAD

**Issue by ReklatsMasters** [ashtuchkin/iconv-lite#93]
I do not quite understand how to convert a string from one encoding to another. Can you create simple method `convert`?

Example:
```js
var str_res = iconv.convert(str, from_encoding, to_encoding);
```

**Comment by ashtuchkin** [comment]
No, it's a bad idea. Please read https://github.com/ashtuchkin/iconv-lite/wiki for explanation about how to use iconv-lite correctly.
