### ISSUE TITLE
Support charset unicode-1-1-utf-7

### ISSUE THREAD

**Issue by dcposch** [ashtuchkin/iconv-lite#94]
I tried parsing a lot of mail using `mailparser`. Almost all messages decode correctly, but a few result in the following error:

    Encoding not recognized: 'UNICODE-1-1-UTF-7' (searched as: 'unicode11utf7')

As far as I can tell, this is just UTF7: https://tools.ietf.org/html/rfc1642

    Use of Character Set UTF-7 Within MIME
    [...]
    The MIME character set identifier is UNICODE-1-1-UTF-7.

Should we just add this as a recognized encoding, as a synonym for utf7?

**Comment by ashtuchkin** [comment]
Published new version 0.4.8 with this alias added.

**Comment by dcposch** [comment]
Wow, that was fast! :+1:

**Comment by khalilTN** [comment]
Is this already available on npm ?

**Comment by ashtuchkin** [comment]
It should be.
