### ISSUE TITLE
Overwrite byte in gb18030, addr: 0

### ISSUE THREAD

**Issue by jcppman** [ashtuchkin/iconv-lite#95]
Hi there, 

In my chrome app, I use `iconv-lite` with browserify to decode file from GB18030, it works pretty well when I load the page as html but when I load it as Chrome app, the following error shows up during decoding: `Overwrite byte in gb18030, addr: 0`

Any idea?

**Comment by jcppman** [comment]
sorry, I know what happened. This is not relevant to iconv-lite!

**Comment by ashtuchkin** [comment]
Seems that the character table loading is screwed up, but I need more information to understand what's going on. Do you use browserify to package Chrome app? Can you isolate the bug in a separate mini-project so that I could reproduce it?

**Comment by jcppman** [comment]
Thanks @ashtuchkin , I figured it out while I'm trying to create a minimal project to reproduce this problem. The solution is simple: adding `<meta charset="UTF-8">` to header to avoid those encoding tables to be screwed.

Before setting charset explicitly, the `mappingTable` inside `DBCSCodec` constructor looks like: 

![image](https://cloud.githubusercontent.com/assets/5248918/7214886/199bb64e-e5f2-11e4-8c20-5544d6e8275d.png)

After:

![image](https://cloud.githubusercontent.com/assets/5248918/7214896/5c9594a6-e5f2-11e4-9389-0c5c4e6610d0.png)

One thing I've no idea why is, the chars in those json tables will only be broken in some strange condition, in order to reproduce the problem, I have to be:

- inside a Chrome App
- use AngularJS and enable [ng-csp](https://docs.angularjs.org/api/ng/directive/ngCsp) mode
- inside html, use mustache expression to render some variable `MyValue = {{ myvalue }}` (this step is neccessary, the variable can be anything inside the scope)

**Comment by ashtuchkin** [comment]
Thanks for figuring out what happened, that was weird)
