### ISSUE TITLE
the first value of `iconv.defaultCharSingleByte` seems to stuck

### ISSUE THREAD

**Issue by Mithgol** [ashtuchkin/iconv-lite#96]
Changing `iconv.defaultCharSingleByte` after the first call to `iconv.encode` does not seem to affect the result of a subsequent `iconv.encode`:

![(screenshot)](https://cloud.githubusercontent.com/assets/1088720/7284022/494549c4-e943-11e4-83e8-6ec968fff3df.gif)

Is it the intended behaviour?

**Comment by ashtuchkin** [comment]
Yes, it's used only when creating lookup tables, at the time of codec creation (first usage of encoding), for performance reasons.

As a temporary workaround you can clean the codec cache every time before changing defaultCharSingleByte:
```javascript
iconv._codecDataCache = {};
iconv.defaultCharSingleByte = <new value>;
```

I don't intend to change this behavior as this will be a non-issue once #73 is fixed, so closing for now. Feel free to reopen if you have other suggestions.
