### ISSUE TITLE
Handle BOMs properly when changing encoding

### ISSUE THREAD

**Issue by bpasero** [ashtuchkin/iconv-lite#97]
First of all, kudos for this lib, its very nice!

I think handling of BOMs should be part of the library though. Imagine you have a file with UTF-8 BOM and you save it as cp1252, the BOM should be removed automatically. In addition, if a BOM is found (UTF 8, UTF 16 LE or BE) and the file is saved with one of those encodings, the BOM should be changed to the proper one. In other words:

- if a file has no BOM, do nothing special
- if a file has a BOM, remove it if the encoding is !== UTF 8, 16 LE, 16 BE
- if a file has a BOM that is !== the encoding of [UTF 8, 16 LE, 16 BE] change it accordingly
- if a file has a BOM and the same encoding is used, keep the BOM

**Comment by ashtuchkin** [comment]
Hey Benjamin, thanks, and thanks for the suggestion. Do you have any interface ideas in mind? How do you see it in code (from your side, not internally)?

At the moment we have completely separate operations of decode vs encode, with only strings between them, so I don't really know how to pass this "if file had a BOM" information. We shouldn't keep the BOM in decoded strings, right?

Moreover, right now for UTF8 and UTF16 we pass the data straight to native Node.js implementation, so it might be a bit tricky to handle, although probably possible.

**Comment by bpasero** [comment]
Hi Alexander, thanks for the prompt reply. I was thinking a little bit about what API could work and came to the conclusion that ideally this would all be handled from the encoding name itself. Imagine alongside utf8, utf16le and utf16be we would have utf8_bom, utf16le_bom and utf16be_bom. This would make the choice of BOM very explicit and would also bind it to the actual encoding. In other words, it would not make sense to have an option to set the bom for an encoding that does not know any BOM (e.g. cp1252).

I am currently only using the encode/decode API where imho for encode() this would work nicely:
- encode() would add the BOM if the encoding indicates so
- encode() would remove any BOM if the encoding does not indicate to add a BOM
- encode() would remove any wrong BOMs if a node buffer is passed in in both cases

For decode() its a bit weird though, I have to say. I think decode() should _always_ remove the BOM from the string returned. It could still treat utf8_bom, utf16be_bom and utf16le_bom as utf8, utf16be and utf16le.

**Comment by ashtuchkin** [comment]
Thanks, that makes sense. So basically decode will always remove BOM and all decoded strings would not have it, plus encode would add BOM if required by encoding name, right? I'm also thinking about adding a flag instead of adding encoding names, what do you think about that?

Also, can you describe your use case a bit more, so that I could understand context, if it's not secret of course? Are you working on a text editor?

**Comment by bpasero** [comment]
Basically I would argue that a string should never ever include a BOM because I cannot think of a use case where you would want the BOM in the string. So, decode() looks at BOMs and removes them because it returns a string.

Encode should add the BOM if specified (either by option or encoding name).

In many cases you would want a BOM for UTF16LE and UTF16BE anyways. Because tools cannot know which encoding to use by looking at the bytes. I believe UTF16 without BOM does not make a lot of sense.

I am working for Visual Studio Code (https://code.visualstudio.com/) and iconv-lite is being used for all encoding matters.

**Comment by ashtuchkin** [comment]
Got ya. I love how Microsoft reinvents itself recently. You rock!

Give me a couple of days, I'll add it.

**Comment by bpasero** [comment]
Nice and I will be happy to test it and give feedback!

**Comment by ashtuchkin** [comment]
Hey, I've published v0.4.9 today, would love to hear feedback)

**Comment by bpasero** [comment]
@ashtuchkin great, I think the API is very good. I will give it a try next week and report back how it works.

**Comment by bpasero** [comment]
@ashtuchkin added to our editor and things are smooth so far. thanks for the prompt implementation and responsiveness!

**Comment by ashtuchkin** [comment]
Cool, nice to hear that!

--
Alexander Shtuchkin
