### ISSUE TITLE
Purpose of changing default UTF-16 from BE to LE

### ISSUE THREAD

**Issue by dougwilson** [ashtuchkin/iconv-lite#98]
Hi! I was looking around at the recent changes and recent closed issues, but wasn't able to find the answer to this question:

Why was the default UTF-16 encoding changed from BE to LE (when there is no BOM, and of course, the content contains no space characters, which are atypical in JSON content)?

Yes, I know I can alter the default, but I was just seeking for the reason behind the change so I can evaluate what I want to do when upgrading to the latest version of this module.

Thanks!

**Comment by ashtuchkin** [comment]
AFAIK it's more often used in practice (f.ex. Windows defaults to LE), plus
it's native to Node.js and x86 architecture.

**Comment by ashtuchkin** [comment]
BTW, You've got me thinking, why do we use only spaces? I think I'll add ASCII chars into consideration as well - that would be much more interesting.

**Comment by ashtuchkin** [comment]
Just released v0.4.10 with the improved heuristic (taking into account any ASCII chars, not just spaces). Now, JSON or not, the default encoding should be not really important.

**Comment by dougwilson** [comment]
Cool, that seems to work perfectly :)
