### ISSUE TITLE
node.js v0.12 and iojs v1.8

### ISSUE THREAD

**Issue by jincdream** [ashtuchkin/iconv-lite#99]
var read = fs.createReadStream(fileName,{encoding:'gbk'}).pipe(res)

I can't extendNodeEncodings

**Comment by jincdream** [comment]
var fs = require('fs');
var ph = require('path');
var iconv = require('iconv-lite');
module.exports = function(path,req,write){
  iconv.extendNodeEncodings();
  var read = fs.createReadStream(path,'gbk')
  iconv.undoExtendNodeEncodings();
  return read
}

**Comment by ashtuchkin** [comment]
It seems Node v0.12 doesn't support encoding as a second argument ([see doc] (https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options)), only options dictionary. 

Should work fine when called like you wrote in the first post (`fs.createReadStream(fileName,{encoding:'gbk'})`). Let me know if it doesn't work when called that way.

**Comment by jincdream** [comment]
Oh,sorry~ It doesn't work --> fs.createReadStream(fileName,{encoding:'gbk'})

and error:
    throw new Error('Unknown encoding: ' + encoding);
          ^
Error: Unknown encoding: gbk

**Comment by ashtuchkin** [comment]
Hmm, just checked and it works for me. Can you remove `iconv.undoExtendNodeEncodings()` from your function? The actual read is happening after you return from function, so you shouldn't do this until an 'end' or 'close' event.

**Comment by jincdream** [comment]
It's helpful.
I have two module file :server.js & readGbk.js.
In this problem,server.js require readGbk.js.

readGbk.js:
```javascript
var fs = require('fs');
var ph = require('path');
var iconv = require('iconv-lite');
module.exports = function(path,req,write){
  iconv.extendNodeEncodings();
  var read = fs.createReadStream(path,{encoding:'gbk'})
  iconv.undoExtendNodeEncodings();
  return read
}
```

server.js:
```javascript
readGbk = require('../readGbk');
server.render = function(req,res){
  ....
  readGbk(file).pipe(res)
}
```
Run and throw an error:
```
and error:
throw new Error('Unknown encoding: ' + encoding);
^
Error: Unknown encoding: gbk
```

Now ,
solution A:
readGbk.js:
```javascript
var fs = require('fs');
var ph = require('path');
var iconv = require('iconv-lite');
module.exports = function(path,req,write){
  iconv.extendNodeEncodings();
  var read = fs.createReadStream(path,{encoding:'gbk'})
  
  return read
}
```

solution B:
readGbk.js:
```javascript
var fs = require('fs');
var ph = require('path');
var iconv = require('iconv-lite');
module.exports = function(path,req,write){ 
  var read = fs.createReadStream(path,{encoding:'gbk'})
  return read
}
```
server.js:
```javascript
iconv.extendNodeEncodings();
readGbk = require('../readGbk');
server.render = function(req,res){
  ....
  readGbk(file).pipe(res)
}
```

Thx.

**Comment by ashtuchkin** [comment]
Yeah, you shouldn't call `iconv.undoExtendNodeEncodings();` before the decoding starts :) Glad you worked it out.
